CREATE TABLE IF NOT EXISTS blog_post (
	id CHAR(27) NOT NULL,
	title VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT NULL,
	created_by CHAR(27) NOT NULL,
	PRIMARY KEY (id)
);
